-- 02_data.sql
-- Datos Iniciales de Prueba

-- Inserción de Tipos de Pasaje
INSERT INTO TIPOS_PASAJE (DESCRIPCION, PORCENTAJE_DESCUENTO) VALUES ('NORMAL', 0);
INSERT INTO TIPOS_PASAJE (DESCRIPCION, PORCENTAJE_DESCUENTO) VALUES ('ESTUDIANTIL', 50);
INSERT INTO TIPOS_PASAJE (DESCRIPCION, PORCENTAJE_DESCUENTO) VALUES ('TERCERA EDAD', 50);
INSERT INTO TIPOS_PASAJE (DESCRIPCION, PORCENTAJE_DESCUENTO) VALUES ('DISCAPACIDAD', 50);

-- Inserción de Rutas
INSERT INTO RUTAS (NOMBRE_RUTA, ORIGEN, DESTINO, PRECIO_BASE) VALUES ('RUTA 1: QUITO - GUAYAQUIL', 'QUITO', 'GUAYAQUIL', 12.00);
INSERT INTO RUTAS (NOMBRE_RUTA, ORIGEN, DESTINO, PRECIO_BASE) VALUES ('RUTA 2: QUITO - CUENCA', 'QUITO', 'CUENCA', 10.00);
INSERT INTO RUTAS (NOMBRE_RUTA, ORIGEN, DESTINO, PRECIO_BASE) VALUES ('RUTA 3: GUAYAQUIL - MANTA', 'GUAYAQUIL', 'MANTA', 8.50);
INSERT INTO RUTAS (NOMBRE_RUTA, ORIGEN, DESTINO, PRECIO_BASE) VALUES ('RUTA 4: LOJA - QUITO', 'LOJA', 'QUITO', 15.00);
INSERT INTO RUTAS (NOMBRE_RUTA, ORIGEN, DESTINO, PRECIO_BASE) VALUES ('RUTA 5: IBARRA - QUITO', 'IBARRA', 'QUITO', 3.50);

-- Inserción de Unidades
INSERT INTO UNIDADES (NUMERO_DISCO, PLACA, CAPACIDAD) VALUES ('01', 'PAA-1234', 40);
INSERT INTO UNIDADES (NUMERO_DISCO, PLACA, CAPACIDAD) VALUES ('02', 'PBB-5678', 42);
INSERT INTO UNIDADES (NUMERO_DISCO, PLACA, CAPACIDAD) VALUES ('03', 'PCC-9012', 38);
INSERT INTO UNIDADES (NUMERO_DISCO, PLACA, CAPACIDAD) VALUES ('04', 'PDD-3456', 45);



COMMIT;
